"""``hardmoney.compat.fecfile_validate``: fecfile-validate's result shape over
whole files and single records, and FECfile+'s Column A keys.

The golden pack in ``tests/fixtures/golden/`` (generated by
``examples/golden_fixtures.rs``) is the oracle: its ``MANIFEST.json`` says
what each file must produce and ``f3x.expected_column_a.json`` is the
Column A FECfile+'s calculator should return for the same transactions.
"""

from __future__ import annotations

import datetime
import json
from decimal import Decimal
from pathlib import Path

import pytest

import hardmoney
from conftest import FIXTURES, MINIMAL
from hardmoney.compat import fecfile_validate as fv

GOLDEN = FIXTURES / "golden"
MANIFEST = json.loads((GOLDEN / "MANIFEST.json").read_text())
BY_NAME = {fx["name"]: fx for fx in MANIFEST["fixtures"]}


def golden(name: str) -> Path:
    return GOLDEN / f"{name}.fec"


# --- the mirrored classes ----------------------------------------------------


def test_validation_error_mirrors_fecfile_validate() -> None:
    e = fv.ValidationError("'form_type' is a required property", "form_type")
    assert (e.message, e.path) == ("'form_type' is a required property", "form_type")
    assert e.validator is None and e.instance is None and e.line_no is None
    assert e.severity == "error"
    assert e == fv.ValidationError("'form_type' is a required property", "form_type")
    assert e != fv.ValidationError("other", "form_type")
    assert "form_type" in repr(e)


def test_validation_result_has_independent_default_lists() -> None:
    a, b = fv.ValidationResult(), fv.ValidationResult()
    a.errors.append(fv.ValidationError("x", "y"))
    assert b.errors == [] and b.warnings == []
    assert a.is_acceptable is False and b.is_acceptable is True
    positional = fv.ValidationResult([fv.ValidationError("m", "p")], [])
    assert positional.errors[0].path == "p"
    assert repr(positional) == "<ValidationResult 1 error(s), 0 warning(s)>"


# --- validate_file -----------------------------------------------------------


@pytest.mark.parametrize("name", ["f3x", "f3", "f3p", "f24", "f1m", "f99"])
def test_clean_golden_fixtures_have_no_findings(name: str) -> None:
    result = fv.validate_file(golden(name))
    assert isinstance(result, fv.ValidationResult)
    assert result.errors == [] and result.warnings == []
    assert result.is_acceptable


def test_accepts_bytes_str_and_paths_alike() -> None:
    path = golden("f3x_duplicate_transaction_id")
    from_path = fv.validate_file(path)
    from_bytes = fv.validate_file(path.read_bytes())
    from_str = fv.validate_file(path.read_bytes().decode("utf-8"))
    from_str_path = fv.validate_file(str(path))
    assert from_str_path.errors == from_path.errors and from_str_path.warnings == from_path.warnings
    assert from_path.errors == from_bytes.errors == from_str.errors
    assert len(from_path.errors) == 1


def test_finding_fields_are_populated() -> None:
    [e] = fv.validate_file(golden("f3x_duplicate_transaction_id")).errors
    expected = BY_NAME["f3x_duplicate_transaction_id"]["expected"]["findings"][0]
    assert e.path == expected["field"] == "transaction_id"
    assert e.validator == expected["rule"] == "duplicate_transaction_id"
    assert e.severity == "error"
    assert e.line_no == expected["line_no"] == 4
    assert e.form_type == expected["form_type"] == "SA11B"
    assert e.instance == "SA11AI.1", "the value as filed on line 4"
    assert e.message.startswith("Tran ID SA11AI.1 is NOT UNIQUE")


def test_missing_required_field_names_the_field() -> None:
    [e] = fv.validate_file(golden("f3x_missing_required_field")).errors
    assert e.path == "contributor_last_name"
    assert e.validator == "required_field_empty"
    assert e.instance == ""
    assert (e.line_no, e.form_type) == (3, "SA11AI")


def test_every_manifest_expectation_holds() -> None:
    for fx in MANIFEST["fixtures"]:
        result = fv.validate_file(GOLDEN / fx["file"])
        expected = fx["expected"]
        assert result.is_acceptable is expected["acceptable"], fx["name"]
        assert len(result.errors) == expected["errors"], fx["name"]
        assert len(result.warnings) == expected["warnings"], fx["name"]
        got = [(e.validator, e.severity, e.line_no, e.form_type, e.path or None) for e in result.errors + result.warnings]
        want = [(f["rule"], f["severity"], f["line_no"], f["form_type"], f["field"]) for f in expected["findings"]]
        assert got == want, fx["name"]


def test_every_accepted_real_fixture_has_no_errors(fixture_path: Path) -> None:
    result = fv.validate_file(fixture_path)
    assert result.errors == [], [e.message for e in result.errors]
    for w in result.warnings:
        assert w.severity == "warning" and w.line_no >= 1 and w.validator


def test_header_findings_name_the_header_field_and_have_no_instance() -> None:
    amendment = MINIMAL.replace("F3XN", "F3XA")  # amendment with no FEC-<n> in the header
    result = fv.validate_file(amendment)
    assert result.errors, "an amendment without its original id is rejected"
    assert {e.path for e in result.errors} == {"report_id", "report_number"}
    assert {e.line_no for e in result.errors} == {1}
    assert {e.form_type for e in result.errors} == {"HDR"}
    # The header is not a Line, so there is no value to quote.
    assert {e.instance for e in result.errors} == {None}


def test_unparseable_content_is_one_parse_error_not_an_exception() -> None:
    result = fv.validate_file(b"not a filing at all")
    [e] = result.errors
    assert e.validator == "parse_error"
    assert e.path == ""
    assert e.message
    assert result.warnings == []
    with pytest.raises(TypeError):
        fv.validate_file(12345)  # type: ignore[arg-type]


def test_skipped_lines_become_warnings() -> None:
    text = MINIMAL + "SZ99\x1cC00123456\x1cunknown record\n"
    result = fv.validate_file(text)
    assert result.errors == []
    assert [w.validator for w in result.warnings if w.line_no == 4] == ["unrecognized_form_type"]


# --- validate_record ---------------------------------------------------------

INDIVIDUAL_RECEIPT = {
    "filer_committee_id_number": "C00123456",
    "transaction_id": "SA11AI.1",
    "entity_type": "IND",
    "contributor_last_name": "Smith",
    "contributor_first_name": "Jane",
    "contributor_street_1": "1 Main St",
    "contributor_city": "Springfield",
    "contributor_state": "VA",
    "contributor_zip_code": "22150",
    "contribution_date": "20260315",
    "contribution_amount": "250.00",
    "contribution_aggregate": "250.00",
    "contributor_employer": "Acme",
    "contributor_occupation": "Engineer",
}


def test_record_with_every_field_is_clean() -> None:
    result = fv.validate_record("SA11AI", INDIVIDUAL_RECEIPT)
    assert result.errors == [] and result.warnings == []


def test_record_missing_required_field_reports_that_field() -> None:
    fields = dict(INDIVIDUAL_RECEIPT)
    del fields["contributor_last_name"]
    result = fv.validate_record("SA11AI", fields)
    [e] = result.errors
    assert e.path == "contributor_last_name"
    assert e.validator == "required_field_empty"
    assert e.instance == ""
    assert e.form_type == "SA11AI"
    assert e.line_no == 3, "the record is line 3 of the synthetic filing"


def test_record_too_long_field_matches_fecfile_validate_test() -> None:
    # fecfile-validate's test_invalid_string_character: a 201-character
    # committee name on an F3X cover ends with "is too long"; ours names
    # the limit.
    result = fv.validate_record("F3XN", {"filer_committee_id_number": "C00123456", "committee_name": "a" * 201})
    assert [e.path for e in result.errors if e.validator == "field_too_long"] == ["committee_name"]
    [too_long] = [e for e in result.errors if e.validator == "field_too_long"]
    assert too_long.line_no == 2, "a cover record is validated as the cover"
    assert too_long.instance == "a" * 201
    assert "200" in too_long.message


def test_cover_record_is_validated_as_a_cover() -> None:
    result = fv.validate_record("F3XN", {"filer_committee_id_number": "C00123456"})
    assert not result.is_acceptable
    assert all(e.line_no == 2 and e.form_type == "F3XN" for e in result.errors)
    assert "treasurer_last_name" in {e.path for e in result.errors}
    assert not any(e.validator == "multiple_forms" for e in result.errors)


def test_fecfile_plus_spellings_and_extra_keys_are_accepted() -> None:
    fields = {
        "report_type": "Q1",  # not a .fec field: ignored
        "transaction_type_identifier": "INDIVIDUAL_RECEIPT",  # ignored
        "aggregation_group": "GENERAL",  # ignored
        **{k: v for k, v in INDIVIDUAL_RECEIPT.items() if k != "contributor_zip_code"},
        "contributor_zip": "22150",  # FECfile+'s name for contributor_zip_code
        "back_reference_tran_id_number": "",  # FECfile+'s name for back_reference_tran_id
        "memo_text_description": "",  # FECfile+'s name for memo_text
    }
    assert fv.validate_record("SA11AI", fields).errors == []
    # The alias really lands on the canonical field: a bad value under the
    # FECfile+ spelling is reported under hardmoney's name.
    fields["contributor_zip"] = "ABC"
    result = fv.validate_record("SA11AI", fields)
    [zip_finding] = result.errors + result.warnings
    assert (zip_finding.path, zip_finding.validator, zip_finding.instance) == (
        "contributor_zip_code",
        "invalid_zip_code",
        "ABC",
    )


def test_typed_values_are_written_as_the_wire_format() -> None:
    fields = {
        **INDIVIDUAL_RECEIPT,
        "contribution_date": datetime.date(2026, 3, 15),
        "contribution_amount": Decimal("250.00"),
        "contribution_aggregate": 250,
        "memo_code": True,
        "back_reference_tran_id": "SA11AI.0",  # a parent this record cannot carry
        "back_reference_sched_name": "SA11AI",
        "contributor_middle_name": None,
    }
    result = fv.validate_record("SA11AI", fields)
    assert result.errors == [], [e.message for e in result.errors]
    assert not any(e.validator == "back_reference_not_found" for e in result.errors + result.warnings)
    with pytest.raises(TypeError, match="float"):
        fv.validate_record("SA11AI", {**INDIVIDUAL_RECEIPT, "contribution_amount": 250.0})


def test_bad_values_are_reported_with_the_value() -> None:
    result = fv.validate_record("SA11AI", {**INDIVIDUAL_RECEIPT, "contribution_date": "2026-03-15", "contributor_state": "Virginia"})
    by_path = {e.path: e for e in result.errors + result.warnings}
    assert by_path["contribution_date"].instance == "2026-03-15"
    assert by_path["contribution_date"].validator == "bad_date_format"
    assert by_path["contributor_state"].instance == "Virginia"


def test_unknown_form_type_raises_value_error() -> None:
    with pytest.raises(ValueError, match="SZ99"):
        fv.validate_record("SZ99", {})


@pytest.mark.parametrize("token", ["SB21B", "SC/10", "SD10", "SE", "SF", "H3", "H4", "F24N", "F99", "F1MN"])
def test_any_known_token_validates_without_schedule_placement_errors(token: str) -> None:
    result = fv.validate_record(token, {"filer_committee_id_number": "C00123456"})
    rules = {e.validator for e in result.errors + result.warnings}
    assert "schedule_not_allowed_with_form" not in rules
    assert "multiple_forms" not in rules
    assert "filer_id_mismatch" not in rules


# --- summary_column_a --------------------------------------------------------


def test_line_key_matches_summary_py() -> None:
    assert fv.line_key("11(a)(i)") == "line_11ai"
    assert fv.line_key("11(a)(ii)") == "line_11aii"
    assert fv.line_key("30(a)(ii)") == "line_30aii"
    assert fv.line_key("6(b)") == "line_6b"
    assert fv.line_key("38") == "line_38"


def test_summary_column_a_equals_the_golden_expected_json() -> None:
    expected = {k: Decimal(v) for k, v in json.loads((GOLDEN / "f3x.expected_column_a.json").read_text()).items()}
    got = fv.summary_column_a(golden("f3x"))
    assert got == expected
    assert all(isinstance(v, Decimal) for v in got.values())
    # The values FECfile+'s test_calculate_summary_column_a asserts.
    assert got["line_11ai"] == Decimal("10000.23")
    assert got["line_11aii"] == Decimal("3.77")
    assert got["line_15"] == Decimal("2125.79")
    assert got["line_24"] == Decimal("151.00")
    assert got["line_25"] == Decimal("133.00")
    assert got["line_28d"] == Decimal("604.50")
    # The five lines FECfile+ stubs to zero, derived from H3/H4 here.
    assert got["line_18c"] == Decimal("1000.00")
    assert got["line_21ai"] == Decimal("330.00")
    assert got["line_21aii"] == Decimal("670.00")
    assert got["line_30ai"] == got["line_30aii"] == 0


def test_summary_column_a_recomputes_from_the_schedules_not_the_cover() -> None:
    off = fv.summary_column_a(golden("f3x_cover_off_by_one_cent"))
    assert off == fv.summary_column_a(golden("f3x")), "the cover's cent is ignored"


def test_summary_column_a_on_f3_and_f3p_uses_their_line_labels() -> None:
    f3 = fv.summary_column_a(golden("f3"))
    assert {"line_11ai", "line_11aii", "line_13a", "line_17", "line_20a", "line_23", "line_27"} <= set(f3)
    assert f3["line_11ai"] == Decimal("2500.00") and f3["line_11aii"] == Decimal("150.00")
    f3p = fv.summary_column_a(golden("f3p"))
    assert {"line_17ai", "line_17aii", "line_18", "line_23", "line_28a", "line_6", "line_10"} <= set(f3p)
    assert f3p["line_17ai"] == Decimal("3300.00") and f3p["line_6"] == Decimal("250.00")


def test_summary_column_a_rejects_forms_without_rules() -> None:
    with pytest.raises(hardmoney.UnsupportedForm):
        fv.summary_column_a(golden("f24"))
